### ISSUE TITLE
PDF Does Not Contain Any Information

### ISSUE THREAD

**Issue by drataiczak** [Phaetus/CoCoon#2]
Instruction PDF is just a single blank page.

**Comment by szafranski** [comment]
Yup

**Comment by Phaetus** [comment]
Hi, we just upload the Instruction

**Comment by szafranski** [comment]
Nice. Just kindly reminder that your qrcode from the included paper in the box, now contains missing link
![IMG_0522](https://github.com/user-attachments/assets/1741d2f9-9245-4d4d-b405-758262c7794a)

**Comment by Phaetus** [comment]
Thanks for your reminder. We have updated three QR codes in the box.
